# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: SnykSecurityScan@1
  displayName: 'Scanning Container Image'
  inputs:
    serviceConnectionEndpoint: 'Snyk-devsecops'
    testType: 'container'
    dockerImageName: 'manu03x/polyglot-ms-account:latest'
    dockerfilePath: 'Dockerfile'
    monitorWhen: 'always'
    failOnIssues: false
